# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStockValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='site_app.Company')),
                ('previous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='site_app.CompanyStockValue')),
            ],
        ),
    ]
