# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='persons',
        ),
        migrations.AddField(
            model_name='person',
            name='companies',
            field=models.ManyToManyField(to='site_app.Company'),
        ),
    ]
