# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_auto_20170530_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShareValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='site_app.Company')),
            ],
        ),
    ]
