# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 23:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_auto_20170628_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 28, 20, 59, 50, 351784)),
        ),
    ]
