# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_auto_20170611_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wikipedia',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
