# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_auto_20170628_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wikipedia',
            field=models.CharField(default='acabate', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 0, 25, 50, 379422)),
        ),
    ]
