# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_companysharevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='companies',
            field=models.ManyToManyField(related_name='persons', to='site_app.Company'),
        ),
    ]
