# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_auto_20170702_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='wikipedia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 0, 39, 20, 721536)),
        ),
    ]
