# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_auto_20170531_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysharevalue',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
