# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_company_wikipedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
