# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_auto_20170702_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 7, 3, 0, 51, 0, 678754))),
                ('headline_link', models.TextField()),
                ('headline_text', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='site_app.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 3, 0, 51, 0, 678119)),
        ),
    ]
