# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_auto_20170618_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=40)),
                ('companies', models.ManyToManyField(related_name='users', to='site_app.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='companies',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
