# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 20:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_auto_20170704_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 17, 45, 709261)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 17, 45, 708712)),
        ),
    ]
