# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_auto_20170704_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 20, 16, 64664)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 20, 16, 64123)),
        ),
    ]
