# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_auto_20170709_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stock',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 11, 34, 34, 634381)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 11, 34, 34, 633597)),
        ),
    ]
