# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_auto_20170711_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 11, 35, 11, 475033)),
        ),
        migrations.AlterField(
            model_name='companystockvalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 11, 35, 11, 474396)),
        ),
    ]
